/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedBlogRouteImport } from './routes/_authenticated/blog'
import { Route as AuthenticatedCharterRouteImport } from './routes/_authenticated/charter'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLoyaltyRouteImport } from './routes/_authenticated/loyalty'
import { Route as AuthenticatedMemberRouteImport } from './routes/_authenticated/member'
import { Route as AuthenticatedMindmapRouteImport } from './routes/_authenticated/mindmap'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTerrainRouteImport } from './routes/_authenticated/terrain'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminCockpitRouteImport } from './routes/_authenticated/admin.cockpit'
import { Route as AuthenticatedAdminLoyaltyRulesRouteImport } from './routes/_authenticated/admin.loyalty-rules'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminValidationRouteImport } from './routes/_authenticated/admin.validation'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events.index'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedMembersMemberIdRouteImport } from './routes/_authenticated/members.$memberId'
import { Route as AuthenticatedMembersNewRouteImport } from './routes/_authenticated/members.new'
import { Route as AuthenticatedProfessionalsIndexRouteImport } from './routes/_authenticated/professionals.index'
import { Route as AuthenticatedProfessionalsProIdRouteImport } from './routes/_authenticated/professionals.$proId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as ApiPublicResetDemoRouteImport } from './routes/api/public/reset-demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlogRoute = AuthenticatedBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCharterRoute = AuthenticatedCharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoyaltyRoute = AuthenticatedLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemberRoute = AuthenticatedMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMindmapRoute = AuthenticatedMindmapRouteImport.update({
  id: '/mindmap',
  path: '/mindmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTerrainRoute = AuthenticatedTerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCockpitRoute =
  AuthenticatedAdminCockpitRouteImport.update({
    id: '/admin/cockpit',
    path: '/admin/cockpit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLoyaltyRulesRoute =
  AuthenticatedAdminLoyaltyRulesRouteImport.update({
    id: '/admin/loyalty-rules',
    path: '/admin/loyalty-rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminValidationRoute =
  AuthenticatedAdminValidationRouteImport.update({
    id: '/admin/validation',
    path: '/admin/validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersMemberIdRoute =
  AuthenticatedMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersNewRoute = AuthenticatedMembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfessionalsIndexRoute =
  AuthenticatedProfessionalsIndexRouteImport.update({
    id: '/professionals/',
    path: '/professionals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalsProIdRoute =
  AuthenticatedProfessionalsProIdRouteImport.update({
    id: '/professionals/$proId',
    path: '/professionals/$proId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicResetDemoRoute = ApiPublicResetDemoRouteImport.update({
  id: '/api/public/reset-demo',
  path: '/api/public/reset-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/blog': typeof AuthenticatedBlogRoute
  '/charter': typeof AuthenticatedCharterRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/member': typeof AuthenticatedMemberRoute
  '/mindmap': typeof AuthenticatedMindmapRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/terrain': typeof AuthenticatedTerrainRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cockpit': typeof AuthenticatedAdminCockpitRoute
  '/admin/loyalty-rules': typeof AuthenticatedAdminLoyaltyRulesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/members/new': typeof AuthenticatedMembersNewRoute
  '/professionals/$proId': typeof AuthenticatedProfessionalsProIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/api/public/reset-demo': typeof ApiPublicResetDemoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/professionals/': typeof AuthenticatedProfessionalsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/blog': typeof AuthenticatedBlogRoute
  '/charter': typeof AuthenticatedCharterRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/member': typeof AuthenticatedMemberRoute
  '/mindmap': typeof AuthenticatedMindmapRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/terrain': typeof AuthenticatedTerrainRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cockpit': typeof AuthenticatedAdminCockpitRoute
  '/admin/loyalty-rules': typeof AuthenticatedAdminLoyaltyRulesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/members/new': typeof AuthenticatedMembersNewRoute
  '/professionals/$proId': typeof AuthenticatedProfessionalsProIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/api/public/reset-demo': typeof ApiPublicResetDemoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/professionals': typeof AuthenticatedProfessionalsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/blog': typeof AuthenticatedBlogRoute
  '/_authenticated/charter': typeof AuthenticatedCharterRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/loyalty': typeof AuthenticatedLoyaltyRoute
  '/_authenticated/member': typeof AuthenticatedMemberRoute
  '/_authenticated/mindmap': typeof AuthenticatedMindmapRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/terrain': typeof AuthenticatedTerrainRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/cockpit': typeof AuthenticatedAdminCockpitRoute
  '/_authenticated/admin/loyalty-rules': typeof AuthenticatedAdminLoyaltyRulesRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/_authenticated/members/new': typeof AuthenticatedMembersNewRoute
  '/_authenticated/professionals/$proId': typeof AuthenticatedProfessionalsProIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/api/public/reset-demo': typeof ApiPublicResetDemoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/professionals/': typeof AuthenticatedProfessionalsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/blog'
    | '/charter'
    | '/documents'
    | '/finance'
    | '/inventory'
    | '/loyalty'
    | '/member'
    | '/mindmap'
    | '/notifications'
    | '/partners'
    | '/profile'
    | '/tasks'
    | '/terrain'
    | '/admin/audit'
    | '/admin/cockpit'
    | '/admin/loyalty-rules'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/validation'
    | '/events/$eventId'
    | '/members/$memberId'
    | '/members/new'
    | '/professionals/$proId'
    | '/projects/$projectId'
    | '/api/public/reset-demo'
    | '/admin/'
    | '/events/'
    | '/members/'
    | '/professionals/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/blog'
    | '/charter'
    | '/documents'
    | '/finance'
    | '/inventory'
    | '/loyalty'
    | '/member'
    | '/mindmap'
    | '/notifications'
    | '/partners'
    | '/profile'
    | '/tasks'
    | '/terrain'
    | '/admin/audit'
    | '/admin/cockpit'
    | '/admin/loyalty-rules'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/validation'
    | '/events/$eventId'
    | '/members/$memberId'
    | '/members/new'
    | '/professionals/$proId'
    | '/projects/$projectId'
    | '/api/public/reset-demo'
    | '/admin'
    | '/events'
    | '/members'
    | '/professionals'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/activities'
    | '/_authenticated/blog'
    | '/_authenticated/charter'
    | '/_authenticated/documents'
    | '/_authenticated/finance'
    | '/_authenticated/inventory'
    | '/_authenticated/loyalty'
    | '/_authenticated/member'
    | '/_authenticated/mindmap'
    | '/_authenticated/notifications'
    | '/_authenticated/partners'
    | '/_authenticated/profile'
    | '/_authenticated/tasks'
    | '/_authenticated/terrain'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/cockpit'
    | '/_authenticated/admin/loyalty-rules'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/validation'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/members/$memberId'
    | '/_authenticated/members/new'
    | '/_authenticated/professionals/$proId'
    | '/_authenticated/projects/$projectId'
    | '/api/public/reset-demo'
    | '/_authenticated/admin/'
    | '/_authenticated/events/'
    | '/_authenticated/members/'
    | '/_authenticated/professionals/'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiPublicResetDemoRoute: typeof ApiPublicResetDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog': {
      id: '/_authenticated/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charter': {
      id: '/_authenticated/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof AuthenticatedCharterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loyalty': {
      id: '/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AuthenticatedLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member': {
      id: '/_authenticated/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthenticatedMemberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mindmap': {
      id: '/_authenticated/mindmap'
      path: '/mindmap'
      fullPath: '/mindmap'
      preLoaderRoute: typeof AuthenticatedMindmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terrain': {
      id: '/_authenticated/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof AuthenticatedTerrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cockpit': {
      id: '/_authenticated/admin/cockpit'
      path: '/admin/cockpit'
      fullPath: '/admin/cockpit'
      preLoaderRoute: typeof AuthenticatedAdminCockpitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/loyalty-rules': {
      id: '/_authenticated/admin/loyalty-rules'
      path: '/admin/loyalty-rules'
      fullPath: '/admin/loyalty-rules'
      preLoaderRoute: typeof AuthenticatedAdminLoyaltyRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/validation': {
      id: '/_authenticated/admin/validation'
      path: '/admin/validation'
      fullPath: '/admin/validation'
      preLoaderRoute: typeof AuthenticatedAdminValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$memberId': {
      id: '/_authenticated/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthenticatedMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/new': {
      id: '/_authenticated/members/new'
      path: '/members/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof AuthenticatedMembersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professionals/': {
      id: '/_authenticated/professionals/'
      path: '/professionals'
      fullPath: '/professionals/'
      preLoaderRoute: typeof AuthenticatedProfessionalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professionals/$proId': {
      id: '/_authenticated/professionals/$proId'
      path: '/professionals/$proId'
      fullPath: '/professionals/$proId'
      preLoaderRoute: typeof AuthenticatedProfessionalsProIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/reset-demo': {
      id: '/api/public/reset-demo'
      path: '/api/public/reset-demo'
      fullPath: '/api/public/reset-demo'
      preLoaderRoute: typeof ApiPublicResetDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedBlogRoute: typeof AuthenticatedBlogRoute
  AuthenticatedCharterRoute: typeof AuthenticatedCharterRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLoyaltyRoute: typeof AuthenticatedLoyaltyRoute
  AuthenticatedMemberRoute: typeof AuthenticatedMemberRoute
  AuthenticatedMindmapRoute: typeof AuthenticatedMindmapRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTerrainRoute: typeof AuthenticatedTerrainRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCockpitRoute: typeof AuthenticatedAdminCockpitRoute
  AuthenticatedAdminLoyaltyRulesRoute: typeof AuthenticatedAdminLoyaltyRulesRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminValidationRoute: typeof AuthenticatedAdminValidationRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedMembersMemberIdRoute: typeof AuthenticatedMembersMemberIdRoute
  AuthenticatedMembersNewRoute: typeof AuthenticatedMembersNewRoute
  AuthenticatedProfessionalsProIdRoute: typeof AuthenticatedProfessionalsProIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedProfessionalsIndexRoute: typeof AuthenticatedProfessionalsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedBlogRoute: AuthenticatedBlogRoute,
  AuthenticatedCharterRoute: AuthenticatedCharterRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLoyaltyRoute: AuthenticatedLoyaltyRoute,
  AuthenticatedMemberRoute: AuthenticatedMemberRoute,
  AuthenticatedMindmapRoute: AuthenticatedMindmapRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTerrainRoute: AuthenticatedTerrainRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCockpitRoute: AuthenticatedAdminCockpitRoute,
  AuthenticatedAdminLoyaltyRulesRoute: AuthenticatedAdminLoyaltyRulesRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminValidationRoute: AuthenticatedAdminValidationRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedMembersMemberIdRoute: AuthenticatedMembersMemberIdRoute,
  AuthenticatedMembersNewRoute: AuthenticatedMembersNewRoute,
  AuthenticatedProfessionalsProIdRoute: AuthenticatedProfessionalsProIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedProfessionalsIndexRoute: AuthenticatedProfessionalsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiPublicResetDemoRoute: ApiPublicResetDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
