/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AssociationRouteImport } from './routes/association'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedAdvantagesRouteImport } from './routes/_authenticated/advantages'
import { Route as AuthenticatedBlogRouteImport } from './routes/_authenticated/blog'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCharterRouteImport } from './routes/_authenticated/charter'
import { Route as AuthenticatedContestsRouteImport } from './routes/_authenticated/contests'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFormationsRouteImport } from './routes/_authenticated/formations'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedHelpRequestsRouteImport } from './routes/_authenticated/help-requests'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLoyaltyRouteImport } from './routes/_authenticated/loyalty'
import { Route as AuthenticatedMemberRouteImport } from './routes/_authenticated/member'
import { Route as AuthenticatedMindmapRouteImport } from './routes/_authenticated/mindmap'
import { Route as AuthenticatedMyHistoryRouteImport } from './routes/_authenticated/my-history'
import { Route as AuthenticatedMySpaceRouteImport } from './routes/_authenticated/my-space'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedParticipationsRouteImport } from './routes/_authenticated/participations'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReimbursementsRouteImport } from './routes/_authenticated/reimbursements'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTerrainRouteImport } from './routes/_authenticated/terrain'
import { Route as PartageTokenRouteImport } from './routes/partage.$token'
import { Route as ProProIdRouteImport } from './routes/pro.$proId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAdvisorRouteImport } from './routes/_authenticated/admin.advisor'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminCockpitRouteImport } from './routes/_authenticated/admin.cockpit'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminLoyaltyRulesRouteImport } from './routes/_authenticated/admin.loyalty-rules'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminValidationRouteImport } from './routes/_authenticated/admin.validation'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events.index'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedMembersMemberIdRouteImport } from './routes/_authenticated/members.$memberId'
import { Route as AuthenticatedMembersNewRouteImport } from './routes/_authenticated/members.new'
import { Route as AuthenticatedProfessionalsIndexRouteImport } from './routes/_authenticated/professionals.index'
import { Route as AuthenticatedProfessionalsProIdRouteImport } from './routes/_authenticated/professionals.$proId'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as ApiPublicResetDemoRouteImport } from './routes/api/public/reset-demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationRoute = AssociationRouteImport.update({
  id: '/association',
  path: '/association',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdvantagesRoute = AuthenticatedAdvantagesRouteImport.update({
  id: '/advantages',
  path: '/advantages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlogRoute = AuthenticatedBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCharterRoute = AuthenticatedCharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContestsRoute = AuthenticatedContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormationsRoute = AuthenticatedFormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRequestsRoute =
  AuthenticatedHelpRequestsRouteImport.update({
    id: '/help-requests',
    path: '/help-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoyaltyRoute = AuthenticatedLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemberRoute = AuthenticatedMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMindmapRoute = AuthenticatedMindmapRouteImport.update({
  id: '/mindmap',
  path: '/mindmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyHistoryRoute = AuthenticatedMyHistoryRouteImport.update({
  id: '/my-history',
  path: '/my-history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySpaceRoute = AuthenticatedMySpaceRouteImport.update({
  id: '/my-space',
  path: '/my-space',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParticipationsRoute =
  AuthenticatedParticipationsRouteImport.update({
    id: '/participations',
    path: '/participations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReimbursementsRoute =
  AuthenticatedReimbursementsRouteImport.update({
    id: '/reimbursements',
    path: '/reimbursements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTerrainRoute = AuthenticatedTerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PartageTokenRoute = PartageTokenRouteImport.update({
  id: '/partage/$token',
  path: '/partage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProProIdRoute = ProProIdRouteImport.update({
  id: '/pro/$proId',
  path: '/pro/$proId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAdvisorRoute =
  AuthenticatedAdminAdvisorRouteImport.update({
    id: '/admin/advisor',
    path: '/admin/advisor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCockpitRoute =
  AuthenticatedAdminCockpitRouteImport.update({
    id: '/admin/cockpit',
    path: '/admin/cockpit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLoyaltyRulesRoute =
  AuthenticatedAdminLoyaltyRulesRouteImport.update({
    id: '/admin/loyalty-rules',
    path: '/admin/loyalty-rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminValidationRoute =
  AuthenticatedAdminValidationRouteImport.update({
    id: '/admin/validation',
    path: '/admin/validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersMemberIdRoute =
  AuthenticatedMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersNewRoute = AuthenticatedMembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfessionalsIndexRoute =
  AuthenticatedProfessionalsIndexRouteImport.update({
    id: '/professionals/',
    path: '/professionals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalsProIdRoute =
  AuthenticatedProfessionalsProIdRouteImport.update({
    id: '/professionals/$proId',
    path: '/professionals/$proId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicResetDemoRoute = ApiPublicResetDemoRouteImport.update({
  id: '/api/public/reset-demo',
  path: '/api/public/reset-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/association': typeof AssociationRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/advantages': typeof AuthenticatedAdvantagesRoute
  '/blog': typeof AuthenticatedBlogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/charter': typeof AuthenticatedCharterRoute
  '/contests': typeof AuthenticatedContestsRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/formations': typeof AuthenticatedFormationsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/help-requests': typeof AuthenticatedHelpRequestsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/member': typeof AuthenticatedMemberRoute
  '/mindmap': typeof AuthenticatedMindmapRoute
  '/my-history': typeof AuthenticatedMyHistoryRoute
  '/my-space': typeof AuthenticatedMySpaceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/participations': typeof AuthenticatedParticipationsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reimbursements': typeof AuthenticatedReimbursementsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/terrain': typeof AuthenticatedTerrainRoute
  '/partage/$token': typeof PartageTokenRoute
  '/pro/$proId': typeof ProProIdRoute
  '/admin/advisor': typeof AuthenticatedAdminAdvisorRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cockpit': typeof AuthenticatedAdminCockpitRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/loyalty-rules': typeof AuthenticatedAdminLoyaltyRulesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/members/new': typeof AuthenticatedMembersNewRoute
  '/professionals/$proId': typeof AuthenticatedProfessionalsProIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/api/public/reset-demo': typeof ApiPublicResetDemoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/professionals/': typeof AuthenticatedProfessionalsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/association': typeof AssociationRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/advantages': typeof AuthenticatedAdvantagesRoute
  '/blog': typeof AuthenticatedBlogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/charter': typeof AuthenticatedCharterRoute
  '/contests': typeof AuthenticatedContestsRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/formations': typeof AuthenticatedFormationsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/help-requests': typeof AuthenticatedHelpRequestsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/member': typeof AuthenticatedMemberRoute
  '/mindmap': typeof AuthenticatedMindmapRoute
  '/my-history': typeof AuthenticatedMyHistoryRoute
  '/my-space': typeof AuthenticatedMySpaceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/participations': typeof AuthenticatedParticipationsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reimbursements': typeof AuthenticatedReimbursementsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/terrain': typeof AuthenticatedTerrainRoute
  '/partage/$token': typeof PartageTokenRoute
  '/pro/$proId': typeof ProProIdRoute
  '/admin/advisor': typeof AuthenticatedAdminAdvisorRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cockpit': typeof AuthenticatedAdminCockpitRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/loyalty-rules': typeof AuthenticatedAdminLoyaltyRulesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/members/new': typeof AuthenticatedMembersNewRoute
  '/professionals/$proId': typeof AuthenticatedProfessionalsProIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/api/public/reset-demo': typeof ApiPublicResetDemoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/professionals': typeof AuthenticatedProfessionalsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/association': typeof AssociationRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/advantages': typeof AuthenticatedAdvantagesRoute
  '/_authenticated/blog': typeof AuthenticatedBlogRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/charter': typeof AuthenticatedCharterRoute
  '/_authenticated/contests': typeof AuthenticatedContestsRoute
  '/_authenticated/directory': typeof AuthenticatedDirectoryRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/formations': typeof AuthenticatedFormationsRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/help-requests': typeof AuthenticatedHelpRequestsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/loyalty': typeof AuthenticatedLoyaltyRoute
  '/_authenticated/member': typeof AuthenticatedMemberRoute
  '/_authenticated/mindmap': typeof AuthenticatedMindmapRoute
  '/_authenticated/my-history': typeof AuthenticatedMyHistoryRoute
  '/_authenticated/my-space': typeof AuthenticatedMySpaceRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/participations': typeof AuthenticatedParticipationsRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reimbursements': typeof AuthenticatedReimbursementsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/terrain': typeof AuthenticatedTerrainRoute
  '/partage/$token': typeof PartageTokenRoute
  '/pro/$proId': typeof ProProIdRoute
  '/_authenticated/admin/advisor': typeof AuthenticatedAdminAdvisorRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/cockpit': typeof AuthenticatedAdminCockpitRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/loyalty-rules': typeof AuthenticatedAdminLoyaltyRulesRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/_authenticated/members/new': typeof AuthenticatedMembersNewRoute
  '/_authenticated/professionals/$proId': typeof AuthenticatedProfessionalsProIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/api/public/reset-demo': typeof ApiPublicResetDemoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/professionals/': typeof AuthenticatedProfessionalsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/association'
    | '/activities'
    | '/advantages'
    | '/blog'
    | '/calendar'
    | '/charter'
    | '/contests'
    | '/directory'
    | '/documents'
    | '/finance'
    | '/formations'
    | '/help'
    | '/help-requests'
    | '/inventory'
    | '/loyalty'
    | '/member'
    | '/mindmap'
    | '/my-history'
    | '/my-space'
    | '/notifications'
    | '/onboarding'
    | '/participations'
    | '/partners'
    | '/profile'
    | '/reimbursements'
    | '/statistics'
    | '/tasks'
    | '/terrain'
    | '/partage/$token'
    | '/pro/$proId'
    | '/admin/advisor'
    | '/admin/audit'
    | '/admin/cockpit'
    | '/admin/import'
    | '/admin/loyalty-rules'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/validation'
    | '/events/$eventId'
    | '/members/$memberId'
    | '/members/new'
    | '/professionals/$proId'
    | '/projects/$projectId'
    | '/api/public/reset-demo'
    | '/admin/'
    | '/events/'
    | '/members/'
    | '/professionals/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/association'
    | '/activities'
    | '/advantages'
    | '/blog'
    | '/calendar'
    | '/charter'
    | '/contests'
    | '/directory'
    | '/documents'
    | '/finance'
    | '/formations'
    | '/help'
    | '/help-requests'
    | '/inventory'
    | '/loyalty'
    | '/member'
    | '/mindmap'
    | '/my-history'
    | '/my-space'
    | '/notifications'
    | '/onboarding'
    | '/participations'
    | '/partners'
    | '/profile'
    | '/reimbursements'
    | '/statistics'
    | '/tasks'
    | '/terrain'
    | '/partage/$token'
    | '/pro/$proId'
    | '/admin/advisor'
    | '/admin/audit'
    | '/admin/cockpit'
    | '/admin/import'
    | '/admin/loyalty-rules'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/validation'
    | '/events/$eventId'
    | '/members/$memberId'
    | '/members/new'
    | '/professionals/$proId'
    | '/projects/$projectId'
    | '/api/public/reset-demo'
    | '/admin'
    | '/events'
    | '/members'
    | '/professionals'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/association'
    | '/_authenticated/activities'
    | '/_authenticated/advantages'
    | '/_authenticated/blog'
    | '/_authenticated/calendar'
    | '/_authenticated/charter'
    | '/_authenticated/contests'
    | '/_authenticated/directory'
    | '/_authenticated/documents'
    | '/_authenticated/finance'
    | '/_authenticated/formations'
    | '/_authenticated/help'
    | '/_authenticated/help-requests'
    | '/_authenticated/inventory'
    | '/_authenticated/loyalty'
    | '/_authenticated/member'
    | '/_authenticated/mindmap'
    | '/_authenticated/my-history'
    | '/_authenticated/my-space'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/participations'
    | '/_authenticated/partners'
    | '/_authenticated/profile'
    | '/_authenticated/reimbursements'
    | '/_authenticated/statistics'
    | '/_authenticated/tasks'
    | '/_authenticated/terrain'
    | '/partage/$token'
    | '/pro/$proId'
    | '/_authenticated/admin/advisor'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/cockpit'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/loyalty-rules'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/validation'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/members/$memberId'
    | '/_authenticated/members/new'
    | '/_authenticated/professionals/$proId'
    | '/_authenticated/projects/$projectId'
    | '/api/public/reset-demo'
    | '/_authenticated/admin/'
    | '/_authenticated/events/'
    | '/_authenticated/members/'
    | '/_authenticated/professionals/'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssociationRoute: typeof AssociationRoute
  PartageTokenRoute: typeof PartageTokenRoute
  ProProIdRoute: typeof ProProIdRoute
  ApiPublicResetDemoRoute: typeof ApiPublicResetDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/association': {
      id: '/association'
      path: '/association'
      fullPath: '/association'
      preLoaderRoute: typeof AssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advantages': {
      id: '/_authenticated/advantages'
      path: '/advantages'
      fullPath: '/advantages'
      preLoaderRoute: typeof AuthenticatedAdvantagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog': {
      id: '/_authenticated/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charter': {
      id: '/_authenticated/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof AuthenticatedCharterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contests': {
      id: '/_authenticated/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof AuthenticatedContestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formations': {
      id: '/_authenticated/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof AuthenticatedFormationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-requests': {
      id: '/_authenticated/help-requests'
      path: '/help-requests'
      fullPath: '/help-requests'
      preLoaderRoute: typeof AuthenticatedHelpRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loyalty': {
      id: '/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AuthenticatedLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member': {
      id: '/_authenticated/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthenticatedMemberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mindmap': {
      id: '/_authenticated/mindmap'
      path: '/mindmap'
      fullPath: '/mindmap'
      preLoaderRoute: typeof AuthenticatedMindmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-history': {
      id: '/_authenticated/my-history'
      path: '/my-history'
      fullPath: '/my-history'
      preLoaderRoute: typeof AuthenticatedMyHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-space': {
      id: '/_authenticated/my-space'
      path: '/my-space'
      fullPath: '/my-space'
      preLoaderRoute: typeof AuthenticatedMySpaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participations': {
      id: '/_authenticated/participations'
      path: '/participations'
      fullPath: '/participations'
      preLoaderRoute: typeof AuthenticatedParticipationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reimbursements': {
      id: '/_authenticated/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof AuthenticatedReimbursementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terrain': {
      id: '/_authenticated/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof AuthenticatedTerrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/partage/$token': {
      id: '/partage/$token'
      path: '/partage/$token'
      fullPath: '/partage/$token'
      preLoaderRoute: typeof PartageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$proId': {
      id: '/pro/$proId'
      path: '/pro/$proId'
      fullPath: '/pro/$proId'
      preLoaderRoute: typeof ProProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/advisor': {
      id: '/_authenticated/admin/advisor'
      path: '/admin/advisor'
      fullPath: '/admin/advisor'
      preLoaderRoute: typeof AuthenticatedAdminAdvisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cockpit': {
      id: '/_authenticated/admin/cockpit'
      path: '/admin/cockpit'
      fullPath: '/admin/cockpit'
      preLoaderRoute: typeof AuthenticatedAdminCockpitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/loyalty-rules': {
      id: '/_authenticated/admin/loyalty-rules'
      path: '/admin/loyalty-rules'
      fullPath: '/admin/loyalty-rules'
      preLoaderRoute: typeof AuthenticatedAdminLoyaltyRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/validation': {
      id: '/_authenticated/admin/validation'
      path: '/admin/validation'
      fullPath: '/admin/validation'
      preLoaderRoute: typeof AuthenticatedAdminValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$memberId': {
      id: '/_authenticated/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthenticatedMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/new': {
      id: '/_authenticated/members/new'
      path: '/members/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof AuthenticatedMembersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professionals/': {
      id: '/_authenticated/professionals/'
      path: '/professionals'
      fullPath: '/professionals/'
      preLoaderRoute: typeof AuthenticatedProfessionalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professionals/$proId': {
      id: '/_authenticated/professionals/$proId'
      path: '/professionals/$proId'
      fullPath: '/professionals/$proId'
      preLoaderRoute: typeof AuthenticatedProfessionalsProIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/reset-demo': {
      id: '/api/public/reset-demo'
      path: '/api/public/reset-demo'
      fullPath: '/api/public/reset-demo'
      preLoaderRoute: typeof ApiPublicResetDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedAdvantagesRoute: typeof AuthenticatedAdvantagesRoute
  AuthenticatedBlogRoute: typeof AuthenticatedBlogRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCharterRoute: typeof AuthenticatedCharterRoute
  AuthenticatedContestsRoute: typeof AuthenticatedContestsRoute
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedFormationsRoute: typeof AuthenticatedFormationsRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHelpRequestsRoute: typeof AuthenticatedHelpRequestsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLoyaltyRoute: typeof AuthenticatedLoyaltyRoute
  AuthenticatedMemberRoute: typeof AuthenticatedMemberRoute
  AuthenticatedMindmapRoute: typeof AuthenticatedMindmapRoute
  AuthenticatedMyHistoryRoute: typeof AuthenticatedMyHistoryRoute
  AuthenticatedMySpaceRoute: typeof AuthenticatedMySpaceRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedParticipationsRoute: typeof AuthenticatedParticipationsRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReimbursementsRoute: typeof AuthenticatedReimbursementsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTerrainRoute: typeof AuthenticatedTerrainRoute
  AuthenticatedAdminAdvisorRoute: typeof AuthenticatedAdminAdvisorRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCockpitRoute: typeof AuthenticatedAdminCockpitRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminLoyaltyRulesRoute: typeof AuthenticatedAdminLoyaltyRulesRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminValidationRoute: typeof AuthenticatedAdminValidationRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedMembersMemberIdRoute: typeof AuthenticatedMembersMemberIdRoute
  AuthenticatedMembersNewRoute: typeof AuthenticatedMembersNewRoute
  AuthenticatedProfessionalsProIdRoute: typeof AuthenticatedProfessionalsProIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedProfessionalsIndexRoute: typeof AuthenticatedProfessionalsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedAdvantagesRoute: AuthenticatedAdvantagesRoute,
  AuthenticatedBlogRoute: AuthenticatedBlogRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCharterRoute: AuthenticatedCharterRoute,
  AuthenticatedContestsRoute: AuthenticatedContestsRoute,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedFormationsRoute: AuthenticatedFormationsRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHelpRequestsRoute: AuthenticatedHelpRequestsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLoyaltyRoute: AuthenticatedLoyaltyRoute,
  AuthenticatedMemberRoute: AuthenticatedMemberRoute,
  AuthenticatedMindmapRoute: AuthenticatedMindmapRoute,
  AuthenticatedMyHistoryRoute: AuthenticatedMyHistoryRoute,
  AuthenticatedMySpaceRoute: AuthenticatedMySpaceRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedParticipationsRoute: AuthenticatedParticipationsRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReimbursementsRoute: AuthenticatedReimbursementsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTerrainRoute: AuthenticatedTerrainRoute,
  AuthenticatedAdminAdvisorRoute: AuthenticatedAdminAdvisorRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCockpitRoute: AuthenticatedAdminCockpitRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminLoyaltyRulesRoute: AuthenticatedAdminLoyaltyRulesRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminValidationRoute: AuthenticatedAdminValidationRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedMembersMemberIdRoute: AuthenticatedMembersMemberIdRoute,
  AuthenticatedMembersNewRoute: AuthenticatedMembersNewRoute,
  AuthenticatedProfessionalsProIdRoute: AuthenticatedProfessionalsProIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedProfessionalsIndexRoute: AuthenticatedProfessionalsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssociationRoute: AssociationRoute,
  PartageTokenRoute: PartageTokenRoute,
  ProProIdRoute: ProProIdRoute,
  ApiPublicResetDemoRoute: ApiPublicResetDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
